### ISSUE TITLE
unrecognized date format

### ISSUE THREAD

**Issue by Playaowl** [GastonZalba/video-gpx-sync-to-srt#2]
Hi!
I'm trying to join 3D-Video information from walking with my old Qoocam 3D camera. I used a tracker for producing a GPX file in parallel. Now I want to combine these with the coordinates in a subtitle  track, to later process that video with geo information.
I'm getting the error

playaowl@iMac-3 video-gpx-sync-to-srt % python3 process.py                                                                                          
--> PROCESS STARTED <--
	
1 videos have been found.
input/output.mp4
input/output.mp4 has an unrecognized date format 2023-12-08 17:55:55 UTC and cannot be used
1 gpx have been found.
	
--> PROCESS WAS ABORTED WITH ERRORS <--

The date was not initially in the video, but process complained about missing date, so I've put it in with ffmpeg
ffmpeg -i input.mp4_original -metadata creation_time="2023-12-08 18:55:55+0100" -codec copy input/output.mp4

I've currently no idea how to get past that error message.

**Comment by GastonZalba** [comment]
Ty using something like `2023-12-08 17:55:55` with ffmpeg (removing the +0100). Anyway, as soon as I can I'm going to fix the code and add support for that date format.

> The date was not initially in the video

If you can, send me a small sample video file (original from camera, not re-encoded). The script tries to find this value in the `encoded_date` and `recorded_date` fields, and your date is probably stored in another field.

**Comment by GastonZalba** [comment]
I already updated the code and now it should take that date format as valid

**Comment by Playaowl** [comment]
Thanks, with the new code i' moving a bit further. Nevertheless I'm still having the dates wrong. I've sent you links to get the original data. Current run is:
--> PROCESS STARTED <--
	
1 videos have been found.
input/output.mp4
1 gpx have been found.
	
Video name: output.mp4
Duration (sec): 260.093
Start time: 2023-12-08 17:55:55+01:00
End time: 2023-12-08 18:00:15+01:00
-> WARNING: GPX tracks not synced with the video. Check the time zones.
	
	
--> PROCESS WAS COMPLETED <--
------------------------------
-> Time zone GPX: Europe/Berlin
-> Time zone Video: Europe/Berlin
-> Interpolation frequency (sec): 0
-> Offset time (sec): 0
-> Stored date match the end of the recording: False
-> 1 videos not synced
------------------------------

**Comment by Playaowl** [comment]
time entries in the gpx file are <time>2023-12-08T18:55:05+0100</time> actual time of recording was 18:55 CET.

**Comment by GastonZalba** [comment]
@Playaowl Were you able to resolve this? I couldn't download the files you sent me
